import LeftNavBar from "@/components/LeftNavBar";
import "./globals.css";
import { Inter } from "next/font/google";
import UpperNavBar from "@/components/UpperNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ezra Chai | Software Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} selection:bg-lime-400 selection:text-black`}
      >
        <UpperNavBar />
        <LeftNavBar />
        {children}
      </body>
    </html>
  );
}
